[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "diayn"
version = "0.0.1"
authors = [
  { name="Taha Shieenavaz", email="tahashieenavaz@gmail.com" },
]
description = "An efficient implementation of D.I.A.Y.N agent."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["numpy", "torch"]
keywords = ["diayn", "diversity is all you need", "reinforcement learning", "drl"]
license = { file = "LICENSE" }
urls = { Homepage="https://github.com/tahashieenavaz/diayn", Repository="https://github.com/tahashieenavaz/diayn", Documentation="https://github.com/tahashieenavaz/diayn#readme" }

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
diayn = ["*.md", "*.txt"]
